# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: P.G
email: 635232592@qq.com
description: The Blog of JHJ
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://princessgod.github.io/index.html" # the base hostname & protocol for your site
#twitter_username: hemang_kumar
github_username:  PrincessGod
paginate: 5

encoding: utf-8

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
